//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MimshakPitzuin {
    
    private MimshakPitzuinKoteretKovetz koteretKovetzField;
    
    private MimshakPitzuinYeshutGoremPoneLemislaka[] gufHamimshakField;
    
    private MimshakPitzuinReshumatSgira reshumatSgiraField;
    
    /// <remarks/>
    public MimshakPitzuinKoteretKovetz KoteretKovetz {
        get {
            return this.koteretKovetzField;
        }
        set {
            this.koteretKovetzField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("YeshutGoremPoneLemislaka", IsNullable=false)]
    public MimshakPitzuinYeshutGoremPoneLemislaka[] GufHamimshak {
        get {
            return this.gufHamimshakField;
        }
        set {
            this.gufHamimshakField = value;
        }
    }
    
    /// <remarks/>
    public MimshakPitzuinReshumatSgira ReshumatSgira {
        get {
            return this.reshumatSgiraField;
        }
        set {
            this.reshumatSgiraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinKoteretKovetz {
    
    private int sUGMIMSHAKField;
    
    private MimshakPitzuinKoteretKovetzMISPARGIRSATXML mISPARGIRSATXMLField;
    
    private string tAARICHBITZUAField;
    
    private int kODSVIVATAVODAField;
    
    private string mISPARHAKOVETZField;
    
    private System.Nullable<int> mISPARSIDURIField;
    
    private MimshakPitzuinKoteretKovetzNetuneiGoremSholech netuneiGoremSholechField;
    
    private MimshakPitzuinKoteretKovetzNetuneiGoremNimaan netuneiGoremNimaanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-MIMSHAK")]
    public int SUGMIMSHAK {
        get {
            return this.sUGMIMSHAKField;
        }
        set {
            this.sUGMIMSHAKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-GIRSAT-XML")]
    public MimshakPitzuinKoteretKovetzMISPARGIRSATXML MISPARGIRSATXML {
        get {
            return this.mISPARGIRSATXMLField;
        }
        set {
            this.mISPARGIRSATXMLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TAARICH-BITZUA")]
    public string TAARICHBITZUA {
        get {
            return this.tAARICHBITZUAField;
        }
        set {
            this.tAARICHBITZUAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KOD-SVIVAT-AVODA")]
    public int KODSVIVATAVODA {
        get {
            return this.kODSVIVATAVODAField;
        }
        set {
            this.kODSVIVATAVODAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-HAKOVETZ")]
    public string MISPARHAKOVETZ {
        get {
            return this.mISPARHAKOVETZField;
        }
        set {
            this.mISPARHAKOVETZField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-SIDURI", IsNullable=true)]
    public System.Nullable<int> MISPARSIDURI {
        get {
            return this.mISPARSIDURIField;
        }
        set {
            this.mISPARSIDURIField = value;
        }
    }
    
    /// <remarks/>
    public MimshakPitzuinKoteretKovetzNetuneiGoremSholech NetuneiGoremSholech {
        get {
            return this.netuneiGoremSholechField;
        }
        set {
            this.netuneiGoremSholechField = value;
        }
    }
    
    /// <remarks/>
    public MimshakPitzuinKoteretKovetzNetuneiGoremNimaan NetuneiGoremNimaan {
        get {
            return this.netuneiGoremNimaanField;
        }
        set {
            this.netuneiGoremNimaanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum MimshakPitzuinKoteretKovetzMISPARGIRSATXML {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("001")]
    Item001,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinKoteretKovetzNetuneiGoremSholech {
    
    private int kODSHOLECHField;
    
    private int sUGMEZAHESHOLECHField;
    
    private string mISPARZIHUISHOLECHField;
    
    private string sHEMGOREMSHOLECHField;
    
    private string sHEMPRATIISHKESHERSHOLECHField;
    
    private string sHEMMISHPACHAISHKESHERSHOLECHField;
    
    private string mISPARTELEPHONEKAVIISHKESHERSHOLECHField;
    
    private string eMAILISHKESHERSHOLECHField;
    
    private string mISPARCELLULARIISHKESHERSHOLECHField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KOD-SHOLECH")]
    public int KODSHOLECH {
        get {
            return this.kODSHOLECHField;
        }
        set {
            this.kODSHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-SHOLECH")]
    public int SUGMEZAHESHOLECH {
        get {
            return this.sUGMEZAHESHOLECHField;
        }
        set {
            this.sUGMEZAHESHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-ZIHUI-SHOLECH")]
    public string MISPARZIHUISHOLECH {
        get {
            return this.mISPARZIHUISHOLECHField;
        }
        set {
            this.mISPARZIHUISHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-GOREM-SHOLECH")]
    public string SHEMGOREMSHOLECH {
        get {
            return this.sHEMGOREMSHOLECHField;
        }
        set {
            this.sHEMGOREMSHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-PRATI-ISH-KESHER-SHOLECH")]
    public string SHEMPRATIISHKESHERSHOLECH {
        get {
            return this.sHEMPRATIISHKESHERSHOLECHField;
        }
        set {
            this.sHEMPRATIISHKESHERSHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-MISHPACHA-ISH-KESHER-SHOLECH")]
    public string SHEMMISHPACHAISHKESHERSHOLECH {
        get {
            return this.sHEMMISHPACHAISHKESHERSHOLECHField;
        }
        set {
            this.sHEMMISHPACHAISHKESHERSHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-TELEPHONE-KAVI-ISH-KESHER-SHOLECH")]
    public string MISPARTELEPHONEKAVIISHKESHERSHOLECH {
        get {
            return this.mISPARTELEPHONEKAVIISHKESHERSHOLECHField;
        }
        set {
            this.mISPARTELEPHONEKAVIISHKESHERSHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("E-MAIL-ISH-KESHER-SHOLECH")]
    public string EMAILISHKESHERSHOLECH {
        get {
            return this.eMAILISHKESHERSHOLECHField;
        }
        set {
            this.eMAILISHKESHERSHOLECHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-CELLULARI-ISH-KESHER-SHOLECH", IsNullable=true)]
    public string MISPARCELLULARIISHKESHERSHOLECH {
        get {
            return this.mISPARCELLULARIISHKESHERSHOLECHField;
        }
        set {
            this.mISPARCELLULARIISHKESHERSHOLECHField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinKoteretKovetzNetuneiGoremNimaan {
    
    private int kODNIMAANField;
    
    private int sUGMEZAHENIMAANField;
    
    private string mISPARZIHUINIMAANField;
    
    private string mISPARZIHUIETZELYATZRANNIMAANField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KOD-NIMAAN")]
    public int KODNIMAAN {
        get {
            return this.kODNIMAANField;
        }
        set {
            this.kODNIMAANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-NIMAAN")]
    public int SUGMEZAHENIMAAN {
        get {
            return this.sUGMEZAHENIMAANField;
        }
        set {
            this.sUGMEZAHENIMAANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-ZIHUI-NIMAAN")]
    public string MISPARZIHUINIMAAN {
        get {
            return this.mISPARZIHUINIMAANField;
        }
        set {
            this.mISPARZIHUINIMAANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-ZIHUI-ETZEL-YATZRAN-NIMAAN", IsNullable=true)]
    public string MISPARZIHUIETZELYATZRANNIMAAN {
        get {
            return this.mISPARZIHUIETZELYATZRANNIMAANField;
        }
        set {
            this.mISPARZIHUIETZELYATZRANNIMAANField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinYeshutGoremPoneLemislaka {
    
    private System.Nullable<int> sUGPONEField;
    
    private System.Nullable<int> sUGKODMEZAHEPONEField;
    
    private string mISPARMEZAHEPONEField;
    
    private string sHEMGOREMPONEField;
    
    private string mISPARMEZAHEMETAFELField;
    
    private string sHEMPRATIPONELEMISLAKAField;
    
    private string sHEMMISHPACHAPONELEMISLAKAField;
    
    private string mISPARTELEPHONEKAVIPONELEMISLAKAField;
    
    private string eMAILPONELEMISLAKAField;
    
    private string mISPARCELLULARIField;
    
    private MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasik[] pirteiMaasikField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-PONE", IsNullable=true)]
    public System.Nullable<int> SUGPONE {
        get {
            return this.sUGPONEField;
        }
        set {
            this.sUGPONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-KOD-MEZAHE-PONE", IsNullable=true)]
    public System.Nullable<int> SUGKODMEZAHEPONE {
        get {
            return this.sUGKODMEZAHEPONEField;
        }
        set {
            this.sUGKODMEZAHEPONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-PONE", IsNullable=true)]
    public string MISPARMEZAHEPONE {
        get {
            return this.mISPARMEZAHEPONEField;
        }
        set {
            this.mISPARMEZAHEPONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-GOREM-PONE", IsNullable=true)]
    public string SHEMGOREMPONE {
        get {
            return this.sHEMGOREMPONEField;
        }
        set {
            this.sHEMGOREMPONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-METAFEL", IsNullable=true)]
    public string MISPARMEZAHEMETAFEL {
        get {
            return this.mISPARMEZAHEMETAFELField;
        }
        set {
            this.mISPARMEZAHEMETAFELField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-PRATI-PONE-LEMISLAKA", IsNullable=true)]
    public string SHEMPRATIPONELEMISLAKA {
        get {
            return this.sHEMPRATIPONELEMISLAKAField;
        }
        set {
            this.sHEMPRATIPONELEMISLAKAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-MISHPACHA-PONE-LEMISLAKA", IsNullable=true)]
    public string SHEMMISHPACHAPONELEMISLAKA {
        get {
            return this.sHEMMISHPACHAPONELEMISLAKAField;
        }
        set {
            this.sHEMMISHPACHAPONELEMISLAKAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-TELEPHONE-KAVI-PONE-LEMISLAKA", IsNullable=true)]
    public string MISPARTELEPHONEKAVIPONELEMISLAKA {
        get {
            return this.mISPARTELEPHONEKAVIPONELEMISLAKAField;
        }
        set {
            this.mISPARTELEPHONEKAVIPONELEMISLAKAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("E-MAIL-PONE-LEMISLAKA", IsNullable=true)]
    public string EMAILPONELEMISLAKA {
        get {
            return this.eMAILPONELEMISLAKAField;
        }
        set {
            this.eMAILPONELEMISLAKAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-CELLULARI", IsNullable=true)]
    public string MISPARCELLULARI {
        get {
            return this.mISPARCELLULARIField;
        }
        set {
            this.mISPARCELLULARIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PirteiMaasik")]
    public MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasik[] PirteiMaasik {
        get {
            return this.pirteiMaasikField;
        }
        set {
            this.pirteiMaasikField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasik {
    
    private int sUGMEZAHEMAASIKField;
    
    private string mISPARMEZAHEMAASIKField;
    
    private string kODMEZAHEMAASIKETZELYATZRANField;
    
    private string sHEMMAASIKField;
    
    private string kODMEZAHEYATZRANField;
    
    private string sHEMYATZRANField;
    
    private int mISPARTIKNIKUIIMField;
    
    private MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasikPirteiOved[] pirteiOvedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-MAASIK")]
    public int SUGMEZAHEMAASIK {
        get {
            return this.sUGMEZAHEMAASIKField;
        }
        set {
            this.sUGMEZAHEMAASIKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-MAASIK")]
    public string MISPARMEZAHEMAASIK {
        get {
            return this.mISPARMEZAHEMAASIKField;
        }
        set {
            this.mISPARMEZAHEMAASIKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KOD-MEZAHE-MAASIK-ETZEL-YATZRAN", IsNullable=true)]
    public string KODMEZAHEMAASIKETZELYATZRAN {
        get {
            return this.kODMEZAHEMAASIKETZELYATZRANField;
        }
        set {
            this.kODMEZAHEMAASIKETZELYATZRANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-MAASIK", IsNullable=true)]
    public string SHEMMAASIK {
        get {
            return this.sHEMMAASIKField;
        }
        set {
            this.sHEMMAASIKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KOD-MEZAHE-YATZRAN")]
    public string KODMEZAHEYATZRAN {
        get {
            return this.kODMEZAHEYATZRANField;
        }
        set {
            this.kODMEZAHEYATZRANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-YATZRAN")]
    public string SHEMYATZRAN {
        get {
            return this.sHEMYATZRANField;
        }
        set {
            this.sHEMYATZRANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-TIK-NIKUIIM")]
    public int MISPARTIKNIKUIIM {
        get {
            return this.mISPARTIKNIKUIIMField;
        }
        set {
            this.mISPARTIKNIKUIIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PirteiOved")]
    public MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasikPirteiOved[] PirteiOved {
        get {
            return this.pirteiOvedField;
        }
        set {
            this.pirteiOvedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasikPirteiOved {
    
    private int sUGMEZAHEOVEDField;
    
    private string mISPARMEZAHEOVEDField;
    
    private string sHEMPRATIField;
    
    private string sHEMMISHPACHAField;
    
    private string mISPAROVEDETZELMAASIKField;
    
    private string mISPARMISLAKAField;
    
    private string mISPARMEZAHERESHUMAField;
    
    private MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasikPirteiOvedSachKaspeiPitzuimOvedBemutzar[] sachKaspeiPitzuimOvedBemutzarField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-OVED")]
    public int SUGMEZAHEOVED {
        get {
            return this.sUGMEZAHEOVEDField;
        }
        set {
            this.sUGMEZAHEOVEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-OVED")]
    public string MISPARMEZAHEOVED {
        get {
            return this.mISPARMEZAHEOVEDField;
        }
        set {
            this.mISPARMEZAHEOVEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-PRATI")]
    public string SHEMPRATI {
        get {
            return this.sHEMPRATIField;
        }
        set {
            this.sHEMPRATIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHEM-MISHPACHA")]
    public string SHEMMISHPACHA {
        get {
            return this.sHEMMISHPACHAField;
        }
        set {
            this.sHEMMISHPACHAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-OVED-ETZEL-MAASIK", IsNullable=true)]
    public string MISPAROVEDETZELMAASIK {
        get {
            return this.mISPAROVEDETZELMAASIKField;
        }
        set {
            this.mISPAROVEDETZELMAASIKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-MISLAKA", IsNullable=true)]
    public string MISPARMISLAKA {
        get {
            return this.mISPARMISLAKAField;
        }
        set {
            this.mISPARMISLAKAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-RESHUMA", IsNullable=true)]
    public string MISPARMEZAHERESHUMA {
        get {
            return this.mISPARMEZAHERESHUMAField;
        }
        set {
            this.mISPARMEZAHERESHUMAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SachKaspeiPitzuimOvedBemutzar")]
    public MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasikPirteiOvedSachKaspeiPitzuimOvedBemutzar[] SachKaspeiPitzuimOvedBemutzar {
        get {
            return this.sachKaspeiPitzuimOvedBemutzarField;
        }
        set {
            this.sachKaspeiPitzuimOvedBemutzarField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinYeshutGoremPoneLemislakaPirteiMaasikPirteiOvedSachKaspeiPitzuimOvedBemutzar {
    
    private int sUGMUTZARPENSIONIField;
    
    private string mISPARKUPAField;
    
    private decimal eRECHPIDIONPITZUIMMAASIKNOCHECHIField;
    
    private System.Nullable<decimal> eRECHPIDIONPITZUIMMAASIKNOCHECHILEMASField;
    
    private int kODPITZUIMField;
    
    private decimal sACHAKOLERECHPIDIONPITZUIMField;
    
    private string mISPARPOLISAOHESHBONField;
    
    private string tAARICHHAFKADARISHONAField;
    
    private string tAARICHHAFKADAACHRONAField;
    
    private System.Nullable<int> mAMADKASPEIPITZUIMField;
    
    private string tAARICHTOKEFField;
    
    private System.Nullable<decimal> sACHAKOLERECHPIDIONPITZUIMADKNISALETOKEFField;
    
    private string tAARICHMADADYITRAField;
    
    private System.Nullable<decimal> mADADYITRANEKUDOTField;
    
    private System.Nullable<decimal> sHIARUCHPITZUIMMITZTABERBEMADADMECHIRIMField;
    
    private System.Nullable<decimal> sHIARUCHPITZUIMMITZTABERBEMADADHASHKAOTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SUG-MUTZAR-PENSIONI")]
    public int SUGMUTZARPENSIONI {
        get {
            return this.sUGMUTZARPENSIONIField;
        }
        set {
            this.sUGMUTZARPENSIONIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-KUPA")]
    public string MISPARKUPA {
        get {
            return this.mISPARKUPAField;
        }
        set {
            this.mISPARKUPAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ERECH-PIDION-PITZUIM-MAASIK-NOCHECHI")]
    public decimal ERECHPIDIONPITZUIMMAASIKNOCHECHI {
        get {
            return this.eRECHPIDIONPITZUIMMAASIKNOCHECHIField;
        }
        set {
            this.eRECHPIDIONPITZUIMMAASIKNOCHECHIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ERECH-PIDION-PITZUIM-MAASIK-NOCHECHI-LEMAS", IsNullable=true)]
    public System.Nullable<decimal> ERECHPIDIONPITZUIMMAASIKNOCHECHILEMAS {
        get {
            return this.eRECHPIDIONPITZUIMMAASIKNOCHECHILEMASField;
        }
        set {
            this.eRECHPIDIONPITZUIMMAASIKNOCHECHILEMASField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KOD-PITZUIM")]
    public int KODPITZUIM {
        get {
            return this.kODPITZUIMField;
        }
        set {
            this.kODPITZUIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SACH-AKOL-ERECH-PIDION-PITZUIM")]
    public decimal SACHAKOLERECHPIDIONPITZUIM {
        get {
            return this.sACHAKOLERECHPIDIONPITZUIMField;
        }
        set {
            this.sACHAKOLERECHPIDIONPITZUIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-POLISA-O-HESHBON")]
    public string MISPARPOLISAOHESHBON {
        get {
            return this.mISPARPOLISAOHESHBONField;
        }
        set {
            this.mISPARPOLISAOHESHBONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TAARICH-HAFKADA-RISHONA", IsNullable=true)]
    public string TAARICHHAFKADARISHONA {
        get {
            return this.tAARICHHAFKADARISHONAField;
        }
        set {
            this.tAARICHHAFKADARISHONAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TAARICH-HAFKADA-ACHRONA", IsNullable=true)]
    public string TAARICHHAFKADAACHRONA {
        get {
            return this.tAARICHHAFKADAACHRONAField;
        }
        set {
            this.tAARICHHAFKADAACHRONAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MAMAD-KASPEI-PITZUIM", IsNullable=true)]
    public System.Nullable<int> MAMADKASPEIPITZUIM {
        get {
            return this.mAMADKASPEIPITZUIMField;
        }
        set {
            this.mAMADKASPEIPITZUIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TAARICH-TOKEF", IsNullable=true)]
    public string TAARICHTOKEF {
        get {
            return this.tAARICHTOKEFField;
        }
        set {
            this.tAARICHTOKEFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SACH-AKOL-ERECH-PIDION-PITZUIM-AD-KNISA-LETOKEF", IsNullable=true)]
    public System.Nullable<decimal> SACHAKOLERECHPIDIONPITZUIMADKNISALETOKEF {
        get {
            return this.sACHAKOLERECHPIDIONPITZUIMADKNISALETOKEFField;
        }
        set {
            this.sACHAKOLERECHPIDIONPITZUIMADKNISALETOKEFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TAARICH-MADAD-YITRA", IsNullable=true)]
    public string TAARICHMADADYITRA {
        get {
            return this.tAARICHMADADYITRAField;
        }
        set {
            this.tAARICHMADADYITRAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MADAD-YITRA-NEKUDOT", IsNullable=true)]
    public System.Nullable<decimal> MADADYITRANEKUDOT {
        get {
            return this.mADADYITRANEKUDOTField;
        }
        set {
            this.mADADYITRANEKUDOTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHIARUCH-PITZUIM-MITZTABER-BEMADAD-MECHIRIM", IsNullable=true)]
    public System.Nullable<decimal> SHIARUCHPITZUIMMITZTABERBEMADADMECHIRIM {
        get {
            return this.sHIARUCHPITZUIMMITZTABERBEMADADMECHIRIMField;
        }
        set {
            this.sHIARUCHPITZUIMMITZTABERBEMADADMECHIRIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SHIARUCH-PITZUIM-MITZTABER-BEMADAD-HASHKAOT", IsNullable=true)]
    public System.Nullable<decimal> SHIARUCHPITZUIMMITZTABERBEMADADHASHKAOT {
        get {
            return this.sHIARUCHPITZUIMMITZTABERBEMADADHASHKAOTField;
        }
        set {
            this.sHIARUCHPITZUIMMITZTABERBEMADADHASHKAOTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MimshakPitzuinReshumatSgira {
    
    private int mISPARYATZRANIMField;
    
    private int mISPARMAAVIDIMField;
    
    private int mISPARRESHUMOTField;
    
    private decimal mISPAROVDIMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-YATZRANIM")]
    public int MISPARYATZRANIM {
        get {
            return this.mISPARYATZRANIMField;
        }
        set {
            this.mISPARYATZRANIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-MAAVIDIM")]
    public int MISPARMAAVIDIM {
        get {
            return this.mISPARMAAVIDIMField;
        }
        set {
            this.mISPARMAAVIDIMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-RESHUMOT")]
    public int MISPARRESHUMOT {
        get {
            return this.mISPARRESHUMOTField;
        }
        set {
            this.mISPARRESHUMOTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MISPAR-OVDIM")]
    public decimal MISPAROVDIM {
        get {
            return this.mISPAROVDIMField;
        }
        set {
            this.mISPAROVDIMField = value;
        }
    }
}
