//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientYatzran
    {
        public int Client_Id { get; set; }
        public string KodYatzran { get; set; }
        public Nullable<bool> HasData { get; set; }
        public Nullable<System.DateTime> LastDataUpdate { get; set; }
    }
}
