//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsQueue
    {
        public byte Status { get; set; }
        public int Id { get; set; }
        public string MISPAR_ZIHUY { get; set; }
        public System.DateTime EnqueueDate { get; set; }
        public Nullable<System.DateTime> StartProcessDate { get; set; }
        public Nullable<System.DateTime> DequeueDate { get; set; }
    }
}
