//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Event_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> KOD_MEZAHE_YATZRAN { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
