//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileErrorDetail
    {
        public int FileErrorDetail_ID { get; set; }
        public Nullable<int> GoremPone_ID { get; set; }
        public string PERUT_SHGIHA_BERAMAT_KOVETZ { get; set; }
    
        public virtual GoremPone GoremPone { get; set; }
    }
}
