//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoremPone
    {
        public GoremPone()
        {
            this.FileErrorDetails = new HashSet<FileErrorDetail>();
            this.Requests = new HashSet<Request>();
        }
    
        public int GoremPone_ID { get; set; }
        public Nullable<int> FeedbackFile_ID { get; set; }
        public Nullable<int> SUG_PONE { get; set; }
        public Nullable<int> SUG_KOD_MEZAHE_PONE { get; set; }
        public string MISPAR_MEZAHE_PONE { get; set; }
        public string SHEM_GOREM_PONE { get; set; }
        public string MISPAR_MEZAHE_METAFEL { get; set; }
        public string SHEM_PRATI_PONE_LEMISLAKA { get; set; }
        public string SHEM_MISHPACHA_PONE_LEMISLAKA { get; set; }
        public string MISPAR_TELEPHONE_KAVI_PONE_LEMISLAKA { get; set; }
        public string E_MAIL_PONE_LEMISLAKA { get; set; }
        public string MISPAR_CELLULARI { get; set; }
        public Nullable<int> SUG_MIMSHAK_LEGABAV_MUAVAR_HIZUN_CHOZER { get; set; }
        public string SHEM_HAKOVETZ { get; set; }
        public string MISPAR_HAKOVETZ { get; set; }
        public Nullable<int> RAMAT_MASHOV { get; set; }
        public Nullable<int> SUG_MASHOV { get; set; }
        public Nullable<int> KOD_SHGIHA { get; set; }
    
        public virtual FeedbackFile FeedbackFile { get; set; }
        public virtual ICollection<FileErrorDetail> FileErrorDetails { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
