//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IshKesherYeshutMaasik
    {
        public int IshKesherYeshutMaasik_Id { get; set; }
        public int YeshutMaasik_Id { get; set; }
        public string SHEM_PRATI { get; set; }
        public string SHEM_MISHPACHA { get; set; }
        public string MISPAR_TELEPHONE_KAVI { get; set; }
        public string MISPAR_CELLULARI { get; set; }
        public string MISPAR_FAX { get; set; }
        public string E_MAIL { get; set; }
        public string HEAROT { get; set; }
    
        public virtual YeshutMaasik YeshutMaasik { get; set; }
    }
}
