//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kovetz
    {
        public Kovetz()
        {
            this.HeshbonKovetzs = new HashSet<HeshbonKovetz>();
        }
    
        public int Kovetz_Id { get; set; }
        public string FileName { get; set; }
        public System.DateTime LoadDate { get; set; }
        public int SUG_MIMSHAK { get; set; }
        public string MISPAR_GIRSAT_XML { get; set; }
        public Nullable<System.DateTime> TAARICH_BITZUA { get; set; }
        public int KOD_SVIVAT_AVODA { get; set; }
        public int KIVUN_MIMSHAK_XML { get; set; }
        public int KOD_SHOLEACH { get; set; }
        public string SHEM_SHOLEACH { get; set; }
        public Nullable<int> KOD_MEZAHE_METAFEL { get; set; }
        public string SHEM_METAFEL { get; set; }
        public string MEZAHE_HAAVARA { get; set; }
        public string MISPAR_HAKOVETZ { get; set; }
        public int Yatzran_KOD_MEZAHE_YATZRAN { get; set; }
        public string Yatzran_SHEM_YATZRAN { get; set; }
        public int Sgira_KAMUT_YATZRANIM { get; set; }
        public int Sgira_KAMUT_METAFELIM { get; set; }
        public int Sgira_KAMUT_MUTZARIM { get; set; }
        public int Sgira_KAMUT_YESHUYOT_MAASIK { get; set; }
        public int Sgira_KAMUT_YESHUYOT_MEFITZ { get; set; }
        public int Sgira_MISPAR_YESHUYUT_LAKOACH_BAKOVETZ { get; set; }
        public int Sgira_KAMUT_POLISOT { get; set; }
        public string Ahzakot { get; set; }
    
        public virtual ICollection<HeshbonKovetz> HeshbonKovetzs { get; set; }
    }
}
