//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupa
    {
        public int Kupa_Id { get; set; }
        public int YitraLefiGilPrisha_Id { get; set; }
        public Nullable<int> SUG_KUPA { get; set; }
        public Nullable<decimal> SCHUM_KITZVAT_ZIKNA { get; set; }
        public Nullable<decimal> KITZVAT_HODSHIT_TZFUYA { get; set; }
        public Nullable<decimal> ACHUZ_TSUA_BATACHAZIT { get; set; }
        public Nullable<decimal> TOTAL_ITRA_TZFUYA_MECHUSHAV_LEHON_IM_PREMIOT { get; set; }
        public Nullable<decimal> TZVIRAT_CHISACHON_TZFUYA_LEHON_LELO_PREMIYOT { get; set; }
        public Nullable<decimal> TOTAL_SCHUM_MTZBR_TZAFUY_LEGIL_PRISHA_MECHUSHAV_LEKITZBA_IM_PREMIYOT { get; set; }
        public Nullable<decimal> TOTAL_SCHUM_MITZVTABER_TZFUY_LEGIL_PRISHA_MECHUSHAV_HAMEYOAD_LEKITZBA_LELO_PREMIYOT { get; set; }
    
        public virtual YitraLefiGilPrisha YitraLefiGilPrisha { get; set; }
    }
}
