//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metafel
    {
        public Metafel()
        {
            this.IshKesherMetafels = new HashSet<IshKesherMetafel>();
            this.HeshbonOPolisas = new HashSet<HeshbonOPolisa>();
        }
    
        public int KOD_MEZAHE_METAFEL { get; set; }
        public string SHEM_METAFEL { get; set; }
    
        public virtual ICollection<IshKesherMetafel> IshKesherMetafels { get; set; }
        public virtual ICollection<HeshbonOPolisa> HeshbonOPolisas { get; set; }
    }
}
