//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeyupeKoach
    {
        public int MeyupeKoach_Id { get; set; }
        public int HeshbonOPolisa_Id { get; set; }
        public int KAYAM_MEYUPE_KOACH { get; set; }
        public Nullable<int> SUG_ZIHUY { get; set; }
        public string MISPAR_ZIHUY { get; set; }
        public string SHEM_MEYUPE_KOACH { get; set; }
    
        public virtual HeshbonOPolisa HeshbonOPolisa { get; set; }
    }
}
