//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miktsoa_Isuk_Tachviv
    {
        public int Miktsoa_Isuk_Tachviv_Id { get; set; }
        public int Kisui_Id { get; set; }
        public string TACHVIVIM_O_ISUKIM { get; set; }
        public string KOD_MIKTZOA { get; set; }
        public string TCHUM_ISUK_CHADASH { get; set; }
    
        public virtual Kisui Kisui { get; set; }
    }
}
