//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mutav
    {
        public int Mutav_Id { get; set; }
        public int Kisui_Id { get; set; }
        public int SUG_ZIHUY_MUTAV { get; set; }
        public Nullable<int> KOD_ZIHUY_MUTAV { get; set; }
        public string MISPAR_ZIHUY_MUTAV { get; set; }
        public string SHEM_PRATI_MUTAV { get; set; }
        public string SHEM_MISHPACHA_MUTAV { get; set; }
        public Nullable<int> SUG_ZIKA { get; set; }
        public Nullable<decimal> ACHUZ_MUTAV { get; set; }
        public Nullable<int> HAGDARAT_MUTAV { get; set; }
        public Nullable<int> MAHUT_MUTAV { get; set; }
    
        public virtual Kisui Kisui { get; set; }
    }
}
