//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MutzarKovetz
    {
        public int Kovetz_Id { get; set; }
        public int Mutzar_Id { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual Kovetz Kovetz { get; set; }
        public virtual Mutzar Mutzar { get; set; }
    }
}
