//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerutYitrot
    {
        public int PerutYitrot_Id { get; set; }
        public int Yitrot_Id { get; set; }
        public Nullable<int> KOD_SUG_ITRA { get; set; }
        public Nullable<int> KOD_SUG_HAFRASHA { get; set; }
        public Nullable<decimal> TOTAL_CHISACHON_MTZBR { get; set; }
        public Nullable<decimal> TOTAL_ERKEI_PIDION { get; set; }
    
        public virtual Yitrot Yitrot { get; set; }
    }
}
