//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PirteiTaktziv
    {
        public PirteiTaktziv()
        {
            this.DmeiNihuls = new HashSet<DmeiNihul>();
            this.HafkadaAchronas = new HashSet<HafkadaAchrona>();
            this.HafkadotMetchilatShanas = new HashSet<HafkadotMetchilatShana>();
            this.HafrashotLePolisas = new HashSet<HafrashotLePolisa>();
            this.MasluleiHashkaas = new HashSet<MasluleiHashkaa>();
            this.Yitrots = new HashSet<Yitrot>();
        }
    
        public int PirteiTaktziv_Id { get; set; }
        public int HeshbonOPolisa_Id { get; set; }
        public int Oved_SUG_TOCHNIT_O_CHESHBON { get; set; }
        public string Oved_MPR_MAASIK_BE_YATZRAN { get; set; }
        public Nullable<int> Oved_STATUS_MAASIK { get; set; }
        public Nullable<int> Oved_SUG_BAAL_HAPOLISA_SHE_EINO_HAMEVUTACH { get; set; }
        public string Oved_MISPAR_BAAL_POLISA_SHEEINO_MEVUTAH { get; set; }
        public string Oved_SHEM_BAAL_POLISA_SHEEINO_MEVUTAH { get; set; }
        public Nullable<int> Haasaka_KOD_CHISHUV_SACHAR_POLISA_O_HESHBON { get; set; }
        public Nullable<decimal> Haasaka_SACHAR_POLISA { get; set; }
        public Nullable<int> Haasaka_KOD_OFEN_HATZMADA { get; set; }
        public Nullable<System.DateTime> Haasaka_TAARICH_MASKORET { get; set; }
        public Nullable<int> Haasaka_ZAKAUT_LELO_TNAI { get; set; }
        public Nullable<int> Haasaka_SEIF_14 { get; set; }
        public Nullable<System.DateTime> Haasaka_TAARICH_TCHILAT_TASHLUM { get; set; }
        public string Gvia_SHEM_MESHALEM { get; set; }
        public int Gvia_SUG_TEUDA_MESHALEM { get; set; }
        public string Gvia_MISPAR_ZIHUY_MESHALEM { get; set; }
        public int Gvia_KOD_EMTZAEI_TASHLUM { get; set; }
        public int Gvia_TADIRUT_TASHLUM { get; set; }
        public int Gvia_CHODESH_YECHUS { get; set; }
        public int Gvia_YOM_GVIYA_BECHODESH { get; set; }
        public int Gvia_OFEN_HATZMADAT_GVIA { get; set; }
        public Nullable<decimal> Gvia_ACHUZ_TAT_SHNATIYOT { get; set; }
        public Nullable<decimal> HafkadotShnatiyot_TOTAL_HAFKADOT_OVED_TAGMULIM_SHANA_NOCHECHIT { get; set; }
        public Nullable<decimal> HafkadotShnatiyot_TOTAL_HAFKADOT_MAAVID_TAGMULIM_SHANA_NOCHECHIT { get; set; }
        public Nullable<decimal> HafkadotShnatiyot_TOTAL_HAFKADOT_PITZUIM_SHANA_NOCHECHIT { get; set; }
        public int ChovPigur_KAYAM_CHOV_O_PIGUR { get; set; }
        public Nullable<System.DateTime> ChovPigur_TAARICH_TECHILAT_PIGUR { get; set; }
        public Nullable<int> ChovPigur_MISPAR_CHODSHEI_PIGUR { get; set; }
        public Nullable<int> ChovPigur_SUG_HOV { get; set; }
        public Nullable<decimal> ChovPigur_TOTAL_CHOVOT_O_PIGURIM { get; set; }
        public Nullable<int> ChovPigur_KSAFIM_LO_MESHUYACHIM_MAASIK { get; set; }
        public Nullable<decimal> HotzaotBafoalLehodeshDivoach_SHEUR_DMEI_NIHUL_HAFKADA { get; set; }
        public Nullable<decimal> HotzaotBafoalLehodeshDivoach_TOTAL_DMEI_NIHUL_HAFKADA { get; set; }
        public Nullable<decimal> HotzaotBafoalLehodeshDivoach_SHEUR_DMEI_NIHUL_TZVIRA { get; set; }
        public Nullable<decimal> HotzaotBafoalLehodeshDivoach_TOTAL_DMEI_NIHUL_TZVIRA { get; set; }
        public Nullable<decimal> HotzaotBafoalLehodeshDivoach_SACH_DMEI_NIHUL_ACHERIM { get; set; }
        public Nullable<decimal> HotzaotBafoalLehodeshDivoach_TOTAL_DMEI_NIHUL_POLISA_O_HESHBON { get; set; }
        public Nullable<decimal> HotzaotBafoalLehodeshDivoach_SACH_DMEI_BITUAH_SHENIGBOO { get; set; }
    
        public virtual HeshbonOPolisa HeshbonOPolisa { get; set; }
        public virtual ICollection<DmeiNihul> DmeiNihuls { get; set; }
        public virtual ICollection<HafkadaAchrona> HafkadaAchronas { get; set; }
        public virtual ICollection<HafkadotMetchilatShana> HafkadotMetchilatShanas { get; set; }
        public virtual ICollection<HafrashotLePolisa> HafrashotLePolisas { get; set; }
        public virtual ICollection<MasluleiHashkaa> MasluleiHashkaas { get; set; }
        public virtual ICollection<Yitrot> Yitrots { get; set; }
    }
}
