//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.RequestErrorDetails = new HashSet<RequestErrorDetail>();
            this.RequestPerYatzrans = new HashSet<RequestPerYatzran>();
        }
    
        public int Request_ID { get; set; }
        public Nullable<int> GoremPone_ID { get; set; }
        public string MISPAR_MISLAKA { get; set; }
        public string MISPAR_MEZAHE_RESHUMA { get; set; }
        public Nullable<int> STATUS_RESHUMA { get; set; }
        public Nullable<int> KOD_SHGIHA_BERAMAT_RESHUMA { get; set; }
    
        public virtual GoremPone GoremPone { get; set; }
        public virtual ICollection<RequestErrorDetail> RequestErrorDetails { get; set; }
        public virtual ICollection<RequestPerYatzran> RequestPerYatzrans { get; set; }
    }
}
