//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yatzran
    {
        public Yatzran()
        {
            this.IshKesherYatzrans = new HashSet<IshKesherYatzran>();
            this.HeshbonOPolisas = new HashSet<HeshbonOPolisa>();
        }
    
        public int KOD_MEZAHE_YATZRAN { get; set; }
        public string SHEM_YATZRAN { get; set; }
    
        public virtual ICollection<IshKesherYatzran> IshKesherYatzrans { get; set; }
        public virtual ICollection<HeshbonOPolisa> HeshbonOPolisas { get; set; }
    }
}
