//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YitraLeTkufa
    {
        public int YitraLeTkufa_Id { get; set; }
        public int Yitrot_Id { get; set; }
        public int KOD_TECHULAT_SHICHVA { get; set; }
        public int REKIV_ITRA_LETKUFA { get; set; }
        public int SUG_ITRA_LETKUFA { get; set; }
        public Nullable<decimal> SACH_ITRA_LESHICHVA_BESHACH { get; set; }
    
        public virtual Yitrot Yitrot { get; set; }
    }
}
