//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadAchzakot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PensionsEntities : DbContext
    {
        public PensionsEntities()
            : base("name=PensionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Halvaa> Halvaas { get; set; }
        public virtual DbSet<HeshbonOPolisa> HeshbonOPolisas { get; set; }
        public virtual DbSet<Kupa> Kupas { get; set; }
        public virtual DbSet<MeyupeKoach> MeyupeKoaches { get; set; }
        public virtual DbSet<Mitryot> Mitryots { get; set; }
        public virtual DbSet<Sheer> Sheers { get; set; }
        public virtual DbSet<Tvia> Tvias { get; set; }
        public virtual DbSet<YitraLefiGilPrisha> YitraLefiGilPrishas { get; set; }
        public virtual DbSet<Kisui> Kisuis { get; set; }
        public virtual DbSet<Mevutach> Mevutaches { get; set; }
        public virtual DbSet<Miktsoa_Isuk_Tachviv> Miktsoa_Isuk_Tachviv { get; set; }
        public virtual DbSet<Mutav> Mutavs { get; set; }
        public virtual DbSet<Tosafot> Tosafots { get; set; }
        public virtual DbSet<DmeiNihul> DmeiNihuls { get; set; }
        public virtual DbSet<HafkadaAchrona> HafkadaAchronas { get; set; }
        public virtual DbSet<HafkadotMetchilatShana> HafkadotMetchilatShanas { get; set; }
        public virtual DbSet<HafrashotLePolisa> HafrashotLePolisas { get; set; }
        public virtual DbSet<MasluleiHashkaa> MasluleiHashkaas { get; set; }
        public virtual DbSet<PerutHafkadaAchrona> PerutHafkadaAchronas { get; set; }
        public virtual DbSet<PerutYitrot> PerutYitrots { get; set; }
        public virtual DbSet<PirteiTaktziv> PirteiTaktzivs { get; set; }
        public virtual DbSet<YitraLeTkufa> YitraLeTkufas { get; set; }
        public virtual DbSet<Yitrot> Yitrots { get; set; }
        public virtual DbSet<IshKesherYeshutMetafel> IshKesherYeshutMetafels { get; set; }
        public virtual DbSet<IshKesherYeshutYatzran> IshKesherYeshutYatzrans { get; set; }
        public virtual DbSet<Kovetz> Kovetzs { get; set; }
        public virtual DbSet<YeshutMetafel> YeshutMetafels { get; set; }
        public virtual DbSet<IshKesherYeshutMaasik> IshKesherYeshutMaasiks { get; set; }
        public virtual DbSet<Mutzar> Mutzars { get; set; }
        public virtual DbSet<YeshutMaasik> YeshutMaasiks { get; set; }
    }
}
