//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadAchzakot
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeshutMetafel
    {
        public YeshutMetafel()
        {
            this.IshKesherYeshutMetafels = new HashSet<IshKesherYeshutMetafel>();
        }
    
        public int YeshutMetafel_Id { get; set; }
        public int Kovetz_Id { get; set; }
        public Nullable<int> KOD_MEZAHE_METAFEL { get; set; }
        public string SHEM_METAFEL { get; set; }
    
        public virtual ICollection<IshKesherYeshutMetafel> IshKesherYeshutMetafels { get; set; }
        public virtual Kovetz Kovetz { get; set; }
    }
}
