//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadAchzakot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yitrot
    {
        public Yitrot()
        {
            this.PerutYitrots = new HashSet<PerutYitrot>();
            this.YitraLeTkufas = new HashSet<YitraLeTkufa>();
        }
    
        public int Yitrot_Id { get; set; }
        public Nullable<int> PirteiTaktziv_Id { get; set; }
        public Nullable<System.DateTime> TAARICH_ERECH_TZVIROT { get; set; }
        public Nullable<System.DateTime> MOED_NEZILUT_TAGMULIM { get; set; }
        public Nullable<decimal> YITRAT_KASPEY_TAGMULIM { get; set; }
        public Nullable<decimal> TZVIRAT_PITZUIM_PTURIM_MAAVIDIM_KODMIM { get; set; }
        public Nullable<decimal> ERECH_PIDION_PITZUIM_LEKITZBA_MAAVIDIM_KODMIM { get; set; }
        public Nullable<decimal> TZVIRAT_PITZUIM_MAAVIDIM_KODMIM_BERETZEF_KITZBA { get; set; }
        public Nullable<decimal> TZVIRAT_PITZUIM_MAAVIDIM_KODMIM_BERETZEF_ZECHUYOT { get; set; }
        public Nullable<decimal> TZVIRAT_PITZUIM_31_12_1999_LEKITZBA { get; set; }
        public Nullable<decimal> ERECH_PIDION_MARKIV_PITZUIM_LEMAS_NOCHECHI { get; set; }
        public Nullable<decimal> ERECH_PIDION_PITZUIM_MAAVIDIM_KODMIM_RETZEF_ZEHUYUT { get; set; }
        public Nullable<decimal> ERECH_PIDION_PITZUIM_LEHON_MAAVIDIM_KODMIM { get; set; }
        public int KAYAM_RETZEF_PITZUIM_KITZBA { get; set; }
        public int KAYAM_RETZEF_ZECHUYOT_PITZUIM { get; set; }
    
        public virtual ICollection<PerutYitrot> PerutYitrots { get; set; }
        public virtual PirteiTaktziv PirteiTaktziv { get; set; }
        public virtual ICollection<YitraLeTkufa> YitraLeTkufas { get; set; }
    }
}
