//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Events
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class MimshakEruim
    {

        private MimshakKoteretKovetz koteretKovetzField;

        private MimshakYeshutGoremPoneLemislaka[] gufHamimshakField;

        private MimshakReshumatSgira reshumatSgiraField;

        /// <remarks/>
        public MimshakKoteretKovetz KoteretKovetz
        {
            get
            {
                return this.koteretKovetzField;
            }
            set
            {
                this.koteretKovetzField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("YeshutGoremPoneLemislaka", IsNullable = false)]
        public MimshakYeshutGoremPoneLemislaka[] GufHamimshak
        {
            get
            {
                return this.gufHamimshakField;
            }
            set
            {
                this.gufHamimshakField = value;
            }
        }

        /// <remarks/>
        public MimshakReshumatSgira ReshumatSgira
        {
            get
            {
                return this.reshumatSgiraField;
            }
            set
            {
                this.reshumatSgiraField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakKoteretKovetz
    {

        private int sUGMIMSHAKField;

        private MimshakKoteretKovetzMISPARGIRSATXML mISPARGIRSATXMLField;

        private string tAARICHBITZUAField;

        private int kODSVIVATAVODAField;

        private string mISPARHAKOVETZField;

        private System.Nullable<int> mISPARSIDURIField;

        private MimshakKoteretKovetzNetuneiGoremSholech netuneiGoremSholechField;

        private MimshakKoteretKovetzNetuneiGoremNimaan netuneiGoremNimaanField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MIMSHAK")]
        public int SUGMIMSHAK
        {
            get
            {
                return this.sUGMIMSHAKField;
            }
            set
            {
                this.sUGMIMSHAKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-GIRSAT-XML")]
        public MimshakKoteretKovetzMISPARGIRSATXML MISPARGIRSATXML
        {
            get
            {
                return this.mISPARGIRSATXMLField;
            }
            set
            {
                this.mISPARGIRSATXMLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAARICH-BITZUA")]
        public string TAARICHBITZUA
        {
            get
            {
                return this.tAARICHBITZUAField;
            }
            set
            {
                this.tAARICHBITZUAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-SVIVAT-AVODA")]
        public int KODSVIVATAVODA
        {
            get
            {
                return this.kODSVIVATAVODAField;
            }
            set
            {
                this.kODSVIVATAVODAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-HAKOVETZ")]
        public string MISPARHAKOVETZ
        {
            get
            {
                return this.mISPARHAKOVETZField;
            }
            set
            {
                this.mISPARHAKOVETZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-SIDURI", IsNullable = true)]
        public System.Nullable<int> MISPARSIDURI
        {
            get
            {
                return this.mISPARSIDURIField;
            }
            set
            {
                this.mISPARSIDURIField = value;
            }
        }

        /// <remarks/>
        public MimshakKoteretKovetzNetuneiGoremSholech NetuneiGoremSholech
        {
            get
            {
                return this.netuneiGoremSholechField;
            }
            set
            {
                this.netuneiGoremSholechField = value;
            }
        }

        /// <remarks/>
        public MimshakKoteretKovetzNetuneiGoremNimaan NetuneiGoremNimaan
        {
            get
            {
                return this.netuneiGoremNimaanField;
            }
            set
            {
                this.netuneiGoremNimaanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum MimshakKoteretKovetzMISPARGIRSATXML
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("001")]
        Item001,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakKoteretKovetzNetuneiGoremSholech
    {

        private int kODSHOLECHField;

        private int sUGMEZAHESHOLECHField;

        private string mISPARZIHUISHOLECHField;

        private string sHEMGOREMSHOLECHField;

        private string sHEMPRATIISHKESHERSHOLECHField;

        private string sHEMMISHPACHAISHKESHERSHOLECHField;

        private string mISPARTELEPHONEKAVIISHKESHERSHOLECHField;

        private string eMAILISHKESHERSHOLECHField;

        private string mISPARCELLULARIISHKESHERSHOLECHField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-SHOLECH")]
        public int KODSHOLECH
        {
            get
            {
                return this.kODSHOLECHField;
            }
            set
            {
                this.kODSHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-SHOLECH")]
        public int SUGMEZAHESHOLECH
        {
            get
            {
                return this.sUGMEZAHESHOLECHField;
            }
            set
            {
                this.sUGMEZAHESHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-ZIHUI-SHOLECH")]
        public string MISPARZIHUISHOLECH
        {
            get
            {
                return this.mISPARZIHUISHOLECHField;
            }
            set
            {
                this.mISPARZIHUISHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-GOREM-SHOLECH")]
        public string SHEMGOREMSHOLECH
        {
            get
            {
                return this.sHEMGOREMSHOLECHField;
            }
            set
            {
                this.sHEMGOREMSHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-PRATI-ISH-KESHER-SHOLECH")]
        public string SHEMPRATIISHKESHERSHOLECH
        {
            get
            {
                return this.sHEMPRATIISHKESHERSHOLECHField;
            }
            set
            {
                this.sHEMPRATIISHKESHERSHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-MISHPACHA-ISH-KESHER-SHOLECH")]
        public string SHEMMISHPACHAISHKESHERSHOLECH
        {
            get
            {
                return this.sHEMMISHPACHAISHKESHERSHOLECHField;
            }
            set
            {
                this.sHEMMISHPACHAISHKESHERSHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-TELEPHONE-KAVI-ISH-KESHER-SHOLECH")]
        public string MISPARTELEPHONEKAVIISHKESHERSHOLECH
        {
            get
            {
                return this.mISPARTELEPHONEKAVIISHKESHERSHOLECHField;
            }
            set
            {
                this.mISPARTELEPHONEKAVIISHKESHERSHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-MAIL-ISH-KESHER-SHOLECH")]
        public string EMAILISHKESHERSHOLECH
        {
            get
            {
                return this.eMAILISHKESHERSHOLECHField;
            }
            set
            {
                this.eMAILISHKESHERSHOLECHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-CELLULARI-ISH-KESHER-SHOLECH", IsNullable = true)]
        public string MISPARCELLULARIISHKESHERSHOLECH
        {
            get
            {
                return this.mISPARCELLULARIISHKESHERSHOLECHField;
            }
            set
            {
                this.mISPARCELLULARIISHKESHERSHOLECHField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakKoteretKovetzNetuneiGoremNimaan
    {

        private int kODNIMAANField;

        private int sUGMEZAHENIMAANField;

        private string mISPARZIHUINIMAANField;

        private string mISPARZIHUIETZELYATZRANNIMAANField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-NIMAAN")]
        public int KODNIMAAN
        {
            get
            {
                return this.kODNIMAANField;
            }
            set
            {
                this.kODNIMAANField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-NIMAAN")]
        public int SUGMEZAHENIMAAN
        {
            get
            {
                return this.sUGMEZAHENIMAANField;
            }
            set
            {
                this.sUGMEZAHENIMAANField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-ZIHUI-NIMAAN")]
        public string MISPARZIHUINIMAAN
        {
            get
            {
                return this.mISPARZIHUINIMAANField;
            }
            set
            {
                this.mISPARZIHUINIMAANField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-ZIHUI-ETZEL-YATZRAN-NIMAAN", IsNullable = true)]
        public string MISPARZIHUIETZELYATZRANNIMAAN
        {
            get
            {
                return this.mISPARZIHUIETZELYATZRANNIMAANField;
            }
            set
            {
                this.mISPARZIHUIETZELYATZRANNIMAANField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislaka
    {

        private System.Nullable<int> sUGPONEField;

        private System.Nullable<int> sUGKODMEZAHEPONEField;

        private string mISPARMEZAHEPONEField;

        private string sHEMGOREMPONEField;

        private string mISPARMEZAHEMETAFELField;

        private string sHEMPRATIPONELEMISLAKAField;

        private string sHEMMISHPACHAPONELEMISLAKAField;

        private string mISPARTELEPHONEKAVIPONELEMISLAKAField;

        private string eMAILPONELEMISLAKAField;

        private string mISPARCELLULARIField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisi[] yeshutLakoachMeidaBsisiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-PONE", IsNullable = true)]
        public System.Nullable<int> SUGPONE
        {
            get
            {
                return this.sUGPONEField;
            }
            set
            {
                this.sUGPONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-KOD-MEZAHE-PONE", IsNullable = true)]
        public System.Nullable<int> SUGKODMEZAHEPONE
        {
            get
            {
                return this.sUGKODMEZAHEPONEField;
            }
            set
            {
                this.sUGKODMEZAHEPONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-PONE", IsNullable = true)]
        public string MISPARMEZAHEPONE
        {
            get
            {
                return this.mISPARMEZAHEPONEField;
            }
            set
            {
                this.mISPARMEZAHEPONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-GOREM-PONE", IsNullable = true)]
        public string SHEMGOREMPONE
        {
            get
            {
                return this.sHEMGOREMPONEField;
            }
            set
            {
                this.sHEMGOREMPONEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-METAFEL", IsNullable = true)]
        public string MISPARMEZAHEMETAFEL
        {
            get
            {
                return this.mISPARMEZAHEMETAFELField;
            }
            set
            {
                this.mISPARMEZAHEMETAFELField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-PRATI-PONE-LEMISLAKA", IsNullable = true)]
        public string SHEMPRATIPONELEMISLAKA
        {
            get
            {
                return this.sHEMPRATIPONELEMISLAKAField;
            }
            set
            {
                this.sHEMPRATIPONELEMISLAKAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-MISHPACHA-PONE-LEMISLAKA", IsNullable = true)]
        public string SHEMMISHPACHAPONELEMISLAKA
        {
            get
            {
                return this.sHEMMISHPACHAPONELEMISLAKAField;
            }
            set
            {
                this.sHEMMISHPACHAPONELEMISLAKAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-TELEPHONE-KAVI-PONE-LEMISLAKA", IsNullable = true)]
        public string MISPARTELEPHONEKAVIPONELEMISLAKA
        {
            get
            {
                return this.mISPARTELEPHONEKAVIPONELEMISLAKAField;
            }
            set
            {
                this.mISPARTELEPHONEKAVIPONELEMISLAKAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("E-MAIL-PONE-LEMISLAKA", IsNullable = true)]
        public string EMAILPONELEMISLAKA
        {
            get
            {
                return this.eMAILPONELEMISLAKAField;
            }
            set
            {
                this.eMAILPONELEMISLAKAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-CELLULARI", IsNullable = true)]
        public string MISPARCELLULARI
        {
            get
            {
                return this.mISPARCELLULARIField;
            }
            set
            {
                this.mISPARCELLULARIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("YeshutLakoachMeidaBsisi")]
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisi[] YeshutLakoachMeidaBsisi
        {
            get
            {
                return this.yeshutLakoachMeidaBsisiField;
            }
            set
            {
                this.yeshutLakoachMeidaBsisiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisi
    {

        private int sUGLAKOACHField;

        private int sUGMEZAHELAKOACHField;

        private string mISPARMEZAHELAKOACHField;

        private string sHEMPRATILAKOACHField;

        private string sHEMMISHPACHALAKOACHField;

        private string sHEMMAASIKField;

        private string kODMEZAHEMAASIKETZELYATZRANField;

        private string kODMEDINAField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEirua[] eiruaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-LAKOACH")]
        public int SUGLAKOACH
        {
            get
            {
                return this.sUGLAKOACHField;
            }
            set
            {
                this.sUGLAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-LAKOACH")]
        public int SUGMEZAHELAKOACH
        {
            get
            {
                return this.sUGMEZAHELAKOACHField;
            }
            set
            {
                this.sUGMEZAHELAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-LAKOACH")]
        public string MISPARMEZAHELAKOACH
        {
            get
            {
                return this.mISPARMEZAHELAKOACHField;
            }
            set
            {
                this.mISPARMEZAHELAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-PRATI-LAKOACH", IsNullable = true)]
        public string SHEMPRATILAKOACH
        {
            get
            {
                return this.sHEMPRATILAKOACHField;
            }
            set
            {
                this.sHEMPRATILAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-MISHPACHA-LAKOACH", IsNullable = true)]
        public string SHEMMISHPACHALAKOACH
        {
            get
            {
                return this.sHEMMISHPACHALAKOACHField;
            }
            set
            {
                this.sHEMMISHPACHALAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-MAASIK", IsNullable = true)]
        public string SHEMMAASIK
        {
            get
            {
                return this.sHEMMAASIKField;
            }
            set
            {
                this.sHEMMAASIKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-MEZAHE-MAASIK-ETZEL-YATZRAN", IsNullable = true)]
        public string KODMEZAHEMAASIKETZELYATZRAN
        {
            get
            {
                return this.kODMEZAHEMAASIKETZELYATZRANField;
            }
            set
            {
                this.kODMEZAHEMAASIKETZELYATZRANField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-MEDINA", IsNullable = true)]
        public string KODMEDINA
        {
            get
            {
                return this.kODMEDINAField;
            }
            set
            {
                this.kODMEDINAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Eirua")]
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEirua[] Eirua
        {
            get
            {
                return this.eiruaField;
            }
            set
            {
                this.eiruaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEirua
    {

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEirua kodEiruaField;

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEirua KodEirua
        {
            get
            {
                return this.kodEiruaField;
            }
            set
            {
                this.kodEiruaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEirua
    {

        private int kODEIRUAField;

        private string mISPARMEZAHERESHUMAField;

        private string mISPARMISLAKAField;

        private string mISPARMISLAKALPNIIYACHOZORETField;

        private int oFENHAAVARATMEIDAMIMISLLAKALELAKOACHField;

        private string tAARICHNECHONUTMEIDAField;

        private string aSMACHTAMISLAKAField;

        private string rESERVAMISLAKAField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoach yipuiKoachField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachim mismachimField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzar mutzarField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-EIRUA")]
        public int KODEIRUA
        {
            get
            {
                return this.kODEIRUAField;
            }
            set
            {
                this.kODEIRUAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-RESHUMA", IsNullable = true)]
        public string MISPARMEZAHERESHUMA
        {
            get
            {
                return this.mISPARMEZAHERESHUMAField;
            }
            set
            {
                this.mISPARMEZAHERESHUMAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-MISLAKA", IsNullable = true)]
        public string MISPARMISLAKA
        {
            get
            {
                return this.mISPARMISLAKAField;
            }
            set
            {
                this.mISPARMISLAKAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-MISLAKA-LPNIIYA-CHOZORET", IsNullable = true)]
        public string MISPARMISLAKALPNIIYACHOZORET
        {
            get
            {
                return this.mISPARMISLAKALPNIIYACHOZORETField;
            }
            set
            {
                this.mISPARMISLAKALPNIIYACHOZORETField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OFEN-HAAVARAT-MEIDA-MIMISLLAKA-LELAKOACH")]
        public int OFENHAAVARATMEIDAMIMISLLAKALELAKOACH
        {
            get
            {
                return this.oFENHAAVARATMEIDAMIMISLLAKALELAKOACHField;
            }
            set
            {
                this.oFENHAAVARATMEIDAMIMISLLAKALELAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAARICH-NECHONUT-MEIDA", IsNullable = true)]
        public string TAARICHNECHONUTMEIDA
        {
            get
            {
                return this.tAARICHNECHONUTMEIDAField;
            }
            set
            {
                this.tAARICHNECHONUTMEIDAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASMACHTA-MISLAKA", IsNullable = true)]
        public string ASMACHTAMISLAKA
        {
            get
            {
                return this.aSMACHTAMISLAKAField;
            }
            set
            {
                this.aSMACHTAMISLAKAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RESERVA-MISLAKA", IsNullable = true)]
        public string RESERVAMISLAKA
        {
            get
            {
                return this.rESERVAMISLAKAField;
            }
            set
            {
                this.rESERVAMISLAKAField = value;
            }
        }

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoach YipuiKoach
        {
            get
            {
                return this.yipuiKoachField;
            }
            set
            {
                this.yipuiKoachField = value;
            }
        }

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachim mismachim
        {
            get
            {
                return this.mismachimField;
            }
            set
            {
                this.mismachimField = value;
            }
        }

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzar Mutzar
        {
            get
            {
                return this.mutzarField;
            }
            set
            {
                this.mutzarField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoach
    {

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachBakashatMefitzLeinianYipuiKoach bakashatMefitzLeinianYipuiKoachField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshot achragotVeharshotField;

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachBakashatMefitzLeinianYipuiKoach BakashatMefitzLeinianYipuiKoach
        {
            get
            {
                return this.bakashatMefitzLeinianYipuiKoachField;
            }
            set
            {
                this.bakashatMefitzLeinianYipuiKoachField = value;
            }
        }

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshot AchragotVeharshot
        {
            get
            {
                return this.achragotVeharshotField;
            }
            set
            {
                this.achragotVeharshotField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachBakashatMefitzLeinianYipuiKoach
    {

        private int tZURAFMISMACHYIPUIKOACHField;

        private string kODZIHUIYIPUIKOACHBEMISLAKAField;

        private int mISMACHZIHUIField;

        private int sUGBAKASHATMEFITZLEEINIANYIPUIKOACHField;

        private int kAYAMMUTZARMUCHRAGField;

        private string tAARICHCHTIMALAKOACHField;

        private string tAARICHCHTIMABAALRISHAIONField;

        private int tOKEFYIPUIKOACHField;

        private string mOEDPKIHAField;

        private int aTARMEUVTACHField;

        private string eRETZField;

        private string sHEMYISHUVField;

        private System.Nullable<int> sEMELYESHUVField;

        private string sHEMRECHOVField;

        private string mISPARBAITField;

        private string mISPARKNISAField;

        private System.Nullable<int> mISPARDIRAField;

        private string mIKUDField;

        private int tADOARField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TZURAF-MISMACH-YIPUI-KOACH")]
        public int TZURAFMISMACHYIPUIKOACH
        {
            get
            {
                return this.tZURAFMISMACHYIPUIKOACHField;
            }
            set
            {
                this.tZURAFMISMACHYIPUIKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-ZIHUI-YIPUI-KOACH-BEMISLAKA", IsNullable = true)]
        public string KODZIHUIYIPUIKOACHBEMISLAKA
        {
            get
            {
                return this.kODZIHUIYIPUIKOACHBEMISLAKAField;
            }
            set
            {
                this.kODZIHUIYIPUIKOACHBEMISLAKAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISMACH-ZIHUI")]
        public int MISMACHZIHUI
        {
            get
            {
                return this.mISMACHZIHUIField;
            }
            set
            {
                this.mISMACHZIHUIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-BAKASHAT-MEFITZ-LEEINIAN-YIPUI-KOACH")]
        public int SUGBAKASHATMEFITZLEEINIANYIPUIKOACH
        {
            get
            {
                return this.sUGBAKASHATMEFITZLEEINIANYIPUIKOACHField;
            }
            set
            {
                this.sUGBAKASHATMEFITZLEEINIANYIPUIKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KAYAM-MUTZAR-MUCHRAG")]
        public int KAYAMMUTZARMUCHRAG
        {
            get
            {
                return this.kAYAMMUTZARMUCHRAGField;
            }
            set
            {
                this.kAYAMMUTZARMUCHRAGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAARICH-CHTIMA-LAKOACH")]
        public string TAARICHCHTIMALAKOACH
        {
            get
            {
                return this.tAARICHCHTIMALAKOACHField;
            }
            set
            {
                this.tAARICHCHTIMALAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TAARICH-CHTIMA-BAAL-RISHAION")]
        public string TAARICHCHTIMABAALRISHAION
        {
            get
            {
                return this.tAARICHCHTIMABAALRISHAIONField;
            }
            set
            {
                this.tAARICHCHTIMABAALRISHAIONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TOKEF-YIPUI-KOACH")]
        public int TOKEFYIPUIKOACH
        {
            get
            {
                return this.tOKEFYIPUIKOACHField;
            }
            set
            {
                this.tOKEFYIPUIKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MOED-PKIHA")]
        public string MOEDPKIHA
        {
            get
            {
                return this.mOEDPKIHAField;
            }
            set
            {
                this.mOEDPKIHAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ATAR-MEUVTACH")]
        public int ATARMEUVTACH
        {
            get
            {
                return this.aTARMEUVTACHField;
            }
            set
            {
                this.aTARMEUVTACHField = value;
            }
        }

        /// <remarks/>
        public string ERETZ
        {
            get
            {
                return this.eRETZField;
            }
            set
            {
                this.eRETZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-YISHUV")]
        public string SHEMYISHUV
        {
            get
            {
                return this.sHEMYISHUVField;
            }
            set
            {
                this.sHEMYISHUVField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SEMEL-YESHUV", IsNullable = true)]
        public System.Nullable<int> SEMELYESHUV
        {
            get
            {
                return this.sEMELYESHUVField;
            }
            set
            {
                this.sEMELYESHUVField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-RECHOV", IsNullable = true)]
        public string SHEMRECHOV
        {
            get
            {
                return this.sHEMRECHOVField;
            }
            set
            {
                this.sHEMRECHOVField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-BAIT", IsNullable = true)]
        public string MISPARBAIT
        {
            get
            {
                return this.mISPARBAITField;
            }
            set
            {
                this.mISPARBAITField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-KNISA", IsNullable = true)]
        public string MISPARKNISA
        {
            get
            {
                return this.mISPARKNISAField;
            }
            set
            {
                this.mISPARKNISAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-DIRA", IsNullable = true)]
        public System.Nullable<int> MISPARDIRA
        {
            get
            {
                return this.mISPARDIRAField;
            }
            set
            {
                this.mISPARDIRAField = value;
            }
        }

        /// <remarks/>
        public string MIKUD
        {
            get
            {
                return this.mIKUDField;
            }
            set
            {
                this.mIKUDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TA-DOAR")]
        public int TADOAR
        {
            get
            {
                return this.tADOARField;
            }
            set
            {
                this.tADOARField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshot
    {

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshotMutzarMuchrag[] mutzarMuchragField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshotHarshaaBeramatMutzar[] harshaaBeramatMutzarField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MutzarMuchrag")]
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshotMutzarMuchrag[] MutzarMuchrag
        {
            get
            {
                return this.mutzarMuchragField;
            }
            set
            {
                this.mutzarMuchragField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HarshaaBeramatMutzar")]
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshotHarshaaBeramatMutzar[] HarshaaBeramatMutzar
        {
            get
            {
                return this.harshaaBeramatMutzarField;
            }
            set
            {
                this.harshaaBeramatMutzarField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshotMutzarMuchrag
    {

        private System.Nullable<int> sUGMUTZARMUCHRAGField;

        private string kIDUDMUTZARPENSIONIMUCHRAGField;

        private string mISPARCHESHBONBEMUTZARMUCHRAGField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MUTZAR-MUCHRAG", IsNullable = true)]
        public System.Nullable<int> SUGMUTZARMUCHRAG
        {
            get
            {
                return this.sUGMUTZARMUCHRAGField;
            }
            set
            {
                this.sUGMUTZARMUCHRAGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KIDUD-MUTZAR-PENSIONI-MUCHRAG", IsNullable = true)]
        public string KIDUDMUTZARPENSIONIMUCHRAG
        {
            get
            {
                return this.kIDUDMUTZARPENSIONIMUCHRAGField;
            }
            set
            {
                this.kIDUDMUTZARPENSIONIMUCHRAGField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-CHESHBON-BEMUTZAR-MUCHRAG", IsNullable = true)]
        public string MISPARCHESHBONBEMUTZARMUCHRAG
        {
            get
            {
                return this.mISPARCHESHBONBEMUTZARMUCHRAGField;
            }
            set
            {
                this.mISPARCHESHBONBEMUTZARMUCHRAGField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaYipuiKoachAchragotVeharshotHarshaaBeramatMutzar
    {

        private string kIDUDMUTZARLONITNAHARSHAHAField;

        private string mISPARCHESHBONBEMUTZARLONITNAHARSHAHAField;

        private System.Nullable<int> kABALATMEIDABILVADField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KIDUD-MUTZAR-LO-NITNA-HARSHAHA", IsNullable = true)]
        public string KIDUDMUTZARLONITNAHARSHAHA
        {
            get
            {
                return this.kIDUDMUTZARLONITNAHARSHAHAField;
            }
            set
            {
                this.kIDUDMUTZARLONITNAHARSHAHAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-CHESHBON-BEMUTZAR-LO-NITNA-HARSHAHA", IsNullable = true)]
        public string MISPARCHESHBONBEMUTZARLONITNAHARSHAHA
        {
            get
            {
                return this.mISPARCHESHBONBEMUTZARLONITNAHARSHAHAField;
            }
            set
            {
                this.mISPARCHESHBONBEMUTZARLONITNAHARSHAHAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KABALAT-MEIDA-BILVAD", IsNullable = true)]
        public System.Nullable<int> KABALATMEIDABILVAD
        {
            get
            {
                return this.kABALATMEIDABILVADField;
            }
            set
            {
                this.kABALATMEIDABILVADField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachim
    {

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachimMismachimNilvimBeramatEirua mismachimNilvimBeramatEiruaField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachimZihuiShemMismachBeramatEirua[] zihuiShemMismachBeramatEiruaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mismachim-Nilvim-Beramat-Eirua")]
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachimMismachimNilvimBeramatEirua mismachimNilvimBeramatEirua
        {
            get
            {
                return this.mismachimNilvimBeramatEiruaField;
            }
            set
            {
                this.mismachimNilvimBeramatEiruaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZihuiShemMismachBeramatEirua")]
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachimZihuiShemMismachBeramatEirua[] ZihuiShemMismachBeramatEirua
        {
            get
            {
                return this.zihuiShemMismachBeramatEiruaField;
            }
            set
            {
                this.zihuiShemMismachBeramatEiruaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachimMismachimNilvimBeramatEirua
    {

        private int kOLMISMACHIMTZURFUField;

        private int tFASIMDRUSHIMCHATUMIMField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOL-MISMACHIM-TZURFU")]
        public int KOLMISMACHIMTZURFU
        {
            get
            {
                return this.kOLMISMACHIMTZURFUField;
            }
            set
            {
                this.kOLMISMACHIMTZURFUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TFASIM-DRUSHIM-CHATUMIM")]
        public int TFASIMDRUSHIMCHATUMIM
        {
            get
            {
                return this.tFASIMDRUSHIMCHATUMIMField;
            }
            set
            {
                this.tFASIMDRUSHIMCHATUMIMField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMismachimZihuiShemMismachBeramatEirua
    {

        private string sHEMKOVETZSHELMISMACHBERAMATEIRUAVEBERAMATLAKOACHField;

        private int sUGMISMACHField;

        private string aSMACHTAKOVEZField;

        private int cHATIMAGRAFITField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-KOVETZ-SHEL-MISMACH-BERAMAT-EIRUA-VEBERAMAT-LAKOACH")]
        public string SHEMKOVETZSHELMISMACHBERAMATEIRUAVEBERAMATLAKOACH
        {
            get
            {
                return this.sHEMKOVETZSHELMISMACHBERAMATEIRUAVEBERAMATLAKOACHField;
            }
            set
            {
                this.sHEMKOVETZSHELMISMACHBERAMATEIRUAVEBERAMATLAKOACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MISMACH")]
        public int SUGMISMACH
        {
            get
            {
                return this.sUGMISMACHField;
            }
            set
            {
                this.sUGMISMACHField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ASMACHTA-KOVEZ", IsNullable = true)]
        public string ASMACHTAKOVEZ
        {
            get
            {
                return this.aSMACHTAKOVEZField;
            }
            set
            {
                this.aSMACHTAKOVEZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CHATIMA-GRAFIT")]
        public int CHATIMAGRAFIT
        {
            get
            {
                return this.cHATIMAGRAFITField;
            }
            set
            {
                this.cHATIMAGRAFITField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzar
    {

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzar netuneiMutzarField;

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzar NetuneiMutzar
        {
            get
            {
                return this.netuneiMutzarField;
            }
            set
            {
                this.netuneiMutzarField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzar
    {

        private string kODMEZAHEYATZRANField;

        private System.Nullable<int> sUGMUTZARPENSIONIField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzarHeshbonOPolisa heshbonOPolisaField;

        private MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzarBakashaLekabalatMeidaPitzuim bakashaLekabalatMeidaPitzuimField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-MEZAHE-YATZRAN")]
        public string KODMEZAHEYATZRAN
        {
            get
            {
                return this.kODMEZAHEYATZRANField;
            }
            set
            {
                this.kODMEZAHEYATZRANField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MUTZAR-PENSIONI", IsNullable = true)]
        public System.Nullable<int> SUGMUTZARPENSIONI
        {
            get
            {
                return this.sUGMUTZARPENSIONIField;
            }
            set
            {
                this.sUGMUTZARPENSIONIField = value;
            }
        }

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzarHeshbonOPolisa HeshbonOPolisa
        {
            get
            {
                return this.heshbonOPolisaField;
            }
            set
            {
                this.heshbonOPolisaField = value;
            }
        }

        /// <remarks/>
        public MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzarBakashaLekabalatMeidaPitzuim BakashaLekabalatMeidaPitzuim
        {
            get
            {
                return this.bakashaLekabalatMeidaPitzuimField;
            }
            set
            {
                this.bakashaLekabalatMeidaPitzuimField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzarHeshbonOPolisa
    {

        private string sHEMMUTZARField;

        private string kODMUTZARLEFIKIDUDACHIDField;

        private string mISPARPOLISAOHESHBONField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-MUTZAR")]
        public string SHEMMUTZAR
        {
            get
            {
                return this.sHEMMUTZARField;
            }
            set
            {
                this.sHEMMUTZARField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-MUTZAR-LEFI-KIDUD-ACHID")]
        public string KODMUTZARLEFIKIDUDACHID
        {
            get
            {
                return this.kODMUTZARLEFIKIDUDACHIDField;
            }
            set
            {
                this.kODMUTZARLEFIKIDUDACHIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-POLISA-O-HESHBON")]
        public string MISPARPOLISAOHESHBON
        {
            get
            {
                return this.mISPARPOLISAOHESHBONField;
            }
            set
            {
                this.mISPARPOLISAOHESHBONField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakYeshutGoremPoneLemislakaYeshutLakoachMeidaBsisiEiruaKodEiruaMutzarNetuneiMutzarBakashaLekabalatMeidaPitzuim
    {

        private int sUGMEZAHEOVEDField;

        private string mISPARMEZAHEOVEDField;

        private string sHEMPRATIField;

        private string sHEMMISHPACHAField;

        private string kODMUTZARLEFIKIDUDACHIDField;

        private string mISPARPOLISAOHESHBONField;

        private string kODMEDINAField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SUG-MEZAHE-OVED")]
        public int SUGMEZAHEOVED
        {
            get
            {
                return this.sUGMEZAHEOVEDField;
            }
            set
            {
                this.sUGMEZAHEOVEDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-MEZAHE-OVED")]
        public string MISPARMEZAHEOVED
        {
            get
            {
                return this.mISPARMEZAHEOVEDField;
            }
            set
            {
                this.mISPARMEZAHEOVEDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-PRATI")]
        public string SHEMPRATI
        {
            get
            {
                return this.sHEMPRATIField;
            }
            set
            {
                this.sHEMPRATIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHEM-MISHPACHA")]
        public string SHEMMISHPACHA
        {
            get
            {
                return this.sHEMMISHPACHAField;
            }
            set
            {
                this.sHEMMISHPACHAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-MUTZAR-LEFI-KIDUD-ACHID", IsNullable = true)]
        public string KODMUTZARLEFIKIDUDACHID
        {
            get
            {
                return this.kODMUTZARLEFIKIDUDACHIDField;
            }
            set
            {
                this.kODMUTZARLEFIKIDUDACHIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-POLISA-O-HESHBON", IsNullable = true)]
        public string MISPARPOLISAOHESHBON
        {
            get
            {
                return this.mISPARPOLISAOHESHBONField;
            }
            set
            {
                this.mISPARPOLISAOHESHBONField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KOD-MEDINA", IsNullable = true)]
        public string KODMEDINA
        {
            get
            {
                return this.kODMEDINAField;
            }
            set
            {
                this.kODMEDINAField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MimshakReshumatSgira
    {

        private int mISPARYESHUYUTLAKOACHBAKOVETZField;

        private int mISPARBAKASHOTField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-YESHUYUT-LAKOACH-BAKOVETZ")]
        public int MISPARYESHUYUTLAKOACHBAKOVETZ
        {
            get
            {
                return this.mISPARYESHUYUTLAKOACHBAKOVETZField;
            }
            set
            {
                this.mISPARYESHUYUTLAKOACHBAKOVETZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MISPAR-BAKASHOT")]
        public int MISPARBAKASHOT
        {
            get
            {
                return this.mISPARBAKASHOTField;
            }
            set
            {
                this.mISPARBAKASHOTField = value;
            }
        }
    }
}